# Generated by Django 3.2.7 on 2022-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('app_description', models.TextField(blank=True)),
                ('app_is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
